---
- stat: path=/etc/php/7.0/apache2/php.ini
  register: phpapache

- stat: path=/etc/php/7.0/cli/php.ini
  register: phpcli

- include: php-apache.yml
  when: phpapache.stat.exists

- include: php-cli.yml
  when: phpcli.stat.exists
