---
- name: Add repository for Ubuntu
  become: true
  apt_repository: repo={{ php_ppa }}

- name: Update apt
  become: yes
  apt: update_cache=yes

- name: Install PHP Packages
  become: yes
  apt: pkg={{ item }} state=latest
  with_items: "{{ php_packages }}"
  when: php_packages is defined
  notify:
    - restart apache2

- include: configure.yml
